kind: pipeline
type: docker
name: pastebin

trigger:
  branch:
    - master
  when:
    - tag

steps:
  - name: cache
    image: drillster/drone-volume-cache
    settings:
      cache_from: /root/.m2
      cache_to: maven-cache
    volumes:
      - name: maven-cache
        path: /root/.m2

  - name: checkout
    image: plugins/git
    settings:
      depth: 1

  - name: build
    image: maven:latest
    commands:
      - mvn clean package -DskipTests=true

  - name: docker-build
    image: docker:latest
    environment:
      DOCKER_REPO: newgr8player/pastebin
    secrets:
      - source: dockerhub_username
        target: DOCKER_USERNAME
      - source: dockerhub_password
        target: DOCKER_PASSWORD
    commands:
      - docker build -t $DOCKER_REPO:${DRONE_TAG} . --build-arg APP_VERSION=${DRONE_TAG}
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker push $DOCKER_REPO:${DRONE_TAG}
      - docker tag $DOCKER_REPO:${DRONE_TAG} $DOCKER_REPO:latest
      - docker push $DOCKER_REPO:latest

secrets:
  dockerhub_username:
    from_secret: dockerhub_username
  dockerhub_password:
    from_secret: dockerhub_password
